In [4]:
#넘파이(numpy)는 Numberical Python의 약어로서 파이썬에서 데이터 분석과 산술 연산을 하는데 사용되는 가장 기본적인 필수 패키지 중의 하나.
#패키지 설치하기
#(python_env) C:\Class\python_work>conda install numpy -y
import numpy as np #넘파이를 불러올 때 보통 np로 줄여서 표현

#다차원을 지원하는 배열 객체(ndarray)를 반환
#np.array()메서드는 리스트와 같은 배열 형태로부터 ndarray 객체를 생성하는 가장 기본적인 방법
data = np.array([10,20,30,40])
print(type(data))
print('-' * 30)

print(data)
print('-' * 30)

#data.dtype은 객체 data의 데이터 형(type)를 구함.
#실행 결과로 얻은 int64는 객체 data 요소의 데이터 형이 64비트 정수형이라는 것을 나타냄
print(data.dtype)
print('-' * 30)

print(data[1])

<class 'numpy.ndarray'>
------------------------------
[10 20 30 40]
------------------------------
int64
------------------------------
20


In [7]:
#random.randn()메서드를 이용하여 2차원(2행3열)의 실수형 랜덤수를 생성
data = np.random.randn(2,3)
print(data)
print('-' * 30)
#ndarray 객체 data가 몇 행 몇 열로 구성되어 있는지를 알려줌
print(data.shape)
print('-' * 30)

#data의 데이터형
print(data.dtype)


[[-0.27391627  0.38175855  0.19495828]
 [ 0.54277868  0.83412738  0.76398907]]
------------------------------
(2, 3)
------------------------------
float64


In [ ]:
#ndarray 객체 요소 값을 모두 0으로 초기화하여 ndarray 객체를 생성
data1 = np.zeros(10)
print(data1)
print(data1.dtype) #64비트 실수

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64


In [10]:
#2행 3열의 0.0으로 최기화된 64비트 실수형 ndarray 객체를 생성
data2 = np.zeros((2,3))
print(data2)
print(data2.dtype)
print('-' * 50)

#dtype=np.int64는 0으로 초기화된 64비트 정수형의 ndarray 개체를 생성
data3 = np.zeros((2,3),dtype=np.int64)
print(data3)

[[0. 0. 0.]
 [0. 0. 0.]]
float64
--------------------------------------------------
[[0 0 0]
 [0 0 0]]


In [11]:
#8개의 요소의 값이 모두 1인 1차원 실수형 ndarray 객체
data1 = np.ones(8)
print(data1)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
#Numpy의 arange() 메서드는 파이썬의 내장 함수인 range()의 사용법과 동일함.
#np.arange(10,121,10)은 10에서 120까지 (10씩 증가)의 범위
data = np.arange(10,121,10)
print(data)
print(data[2])
print(data[5:8]) #5~7

[ 10  20  30  40  50  60  70  80  90 100 110 120]
30
[60 70 80]


In [13]:
#판다스는 데이터 분석을 하는 데 가장 많이 사용되는 패키지.
#for문을 이용하지 않고 배열의 산술 연산을 할 수 있으며 Numpy의 스타일과 유사한 배열 관련 함수 제공
#Numpy가 배열 연산에 특화되어 있다면, Pandas는 열과 행으로 구성된 테이블 형태의 데이터를 다루는 데 초점
#패키지 설치하기
#(python_env) C:\Class\python_work>conda install pandas -y
import pandas as pd

#Series 객체의 기본형(type)은 64비트 정수형
#Series 객체는 1차원 배열의 인덱스와 값으로 구성
obj = pd.Series([5,-4,7,0,12])
print(obj)

0     5
1    -4
2     7
3     0
4    12
dtype: int64


In [16]:
obj = pd.Series([8,-20,-3,13,2])
#obj 객체의 값을 얻음
print(obj.values)
print('-' * 30)
#obj 객체의 인덱스를 얻음
print(obj.index)
print('-' * 30)
#인덱스 2에 해당하는 요소 값
print(obj[2])

[  8 -20  -3  13   2]
------------------------------
RangeIndex(start=0, stop=5, step=1)
------------------------------
-3


In [17]:
pop = pd.Series([98790,34567,23456],index=["서울","부산","대구"])
#Series의 객체 pop의 인덱스와 값을 얻는 데 사용
#items()메서드는 Series 객체에 있는 요소를 튜플 형태,
#item()메서드는 Series 객체에 있는 요소를 튜플 형태, 즉 (indedx,value)로 반환
for i,v in pop.items():
    print("%s : %d명" % (i,v))

서울 : 98790명
부산 : 34567명
대구 : 23456명


In [ ]:
import pandas as pd
data = {"이름":["홍지수","안지영","김성수","최예린"],
        "아이디":["jshond","jyahn","sukim","yrchoi"],
        "비밀번호":["1234","1234","1234","1234"]}

#DataFrame 클래스는 테이블 형태로 된 2차원 자료 구조
frame = pd.DataFrame(data)
print(frame)
print('-' * 50)

member = {"이름":["홍지수","안지영"],
          "나이":[20,23],
          "전화번호":["010-1234-5678","010-5678-1234"]}

#DataFrame에 열 인덱스를 설정하는데, columns를 사용하고 형 인덱스를 설정하는데 index를 사용
frame = pd.DataFrame(member,columns=["이름","전화번호","나이","주소"],index=["01","02"]) #주소는 없어서 NaN으로 출력
print(frame)

    이름     아이디  비밀번호
0  홍지수  jshond  1234
1  안지영   jyahn  1234
2  김성수   sukim  1234
3  최예린  yrchoi  1234
--------------------------------------------------
     이름           전화번호  나이   주소
01  홍지수  010-1234-5678  20  NaN
02  안지영  010-5678-1234  23  NaN
